version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install pre-reqs
          command: |
            export TF_VERSION="0.12.3"
            apt-get update && apt-get -y install curl unzip gnupg2
            curl -skO -L https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
            terraform --version
      # - run:
      #     name: Run Terraform plan
      #     command: |
      #       terraform init
      #       terraform plan
      - run:
          name: Install ruby stuff + TF Kitchen
          command: |
            curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
            curl -sSL https://get.rvm.io | bash -s stable
            source /etc/profile.d/rvm.sh
            rvm requirements
            rvm install 2.4.1
            rvm use 2.4.1 --default
            ruby --version
            gem install kitchen-terraform
      - run:
          name: Move test result files into tests path
          command: |
            find /var/lib/gems/ -name mkmf.log -exec cp "{}" /tmp/ruby_logs \;
          when: on_fail

      - store_artifacts:
          path: /tmp/ruby_logs
