version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install pre-reqs
          command: |
            export TF_VERSION="0.12.3"
            apt-get update && apt-get -y install curl unzip ruby-full
            curl -skO -L https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
            terraform --version
      - run:
          name: Run Terraform plan
          command: |
            terraform init
            terraform plan
      - run:
          name: Install ruby stuff + TF Kitchen
          command: 
            bundle install
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results
